from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pytest

from candidate_screening.persistence import Base, SqlAlchemyUnitOfWork
from candidate_screening.persistence.database import (
    create_async_engine_for_url,
    create_session_factory,
)
from candidate_screening.persistence.orm import CandidateORM, ScreeningSessionORM


@pytest.mark.asyncio
async def test_sqlalchemy_repositories_and_optimistic_version(tmp_path: Path) -> None:
    engine = create_async_engine_for_url(f"sqlite:///{tmp_path / 'screening.db'}")
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    factory = create_session_factory(engine)

    candidate = CandidateORM(full_name="Ana")
    screening = ScreeningSessionORM(candidate_id=candidate.id or "")
    # Defaults are generated by SQLAlchemy at flush time, so use the explicit
    # ID after the candidate is added in one unit of work.
    async with SqlAlchemyUnitOfWork(factory) as uow:
        assert uow.candidates is not None and uow.sessions is not None
        await uow.candidates.add(candidate)
        screening.candidate_id = candidate.id
        await uow.sessions.add(screening)
        await uow.commit()

    async with SqlAlchemyUnitOfWork(factory) as uow:
        assert uow.sessions is not None
        saved = await uow.sessions.save_state(
            screening.id,
            state={"preferred_language": "en"},
            status="in_progress",
            expected_version=1,
            current_field="full_name",
            last_activity_at=datetime.now(UTC),
        )
        assert saved is not None
        assert saved.version == 2
        conflict = await uow.sessions.save_state(
            screening.id,
            state={},
            status="in_progress",
            expected_version=1,
        )
        assert conflict is None
        await uow.commit()

    await engine.dispose()
